### ISSUE TITLE
There was a problem connecting with paypal. 

### ISSUE THREAD

**Issue by bobomimi** [solidusio-contrib/solidus_paypal_commerce_platform#107]
Hey 
after I changed the store default currency in spree.rb from USD to EUR or any other currency, I'm getting this message (There was a problem connecting with paypal.) when I'm clicking the PayPal buttons.
it working fine when it's on USD...
thanks :)

**Comment by seand7565** [comment]
Thanks for the issue report @bobomimi ! This is definitely a problem - PayPals SDK defaults currency to USD and will throw an error if the currency provided doesn't match. I'll have a PR open in a few seconds that handles this, and at some point soon we'll release a minor version update.
