### ISSUE TITLE
Implement and QA Paypal credit solutions

### ISSUE THREAD

**Issue by mtylty** [solidusio-contrib/solidus_paypal_commerce_platform#99]
The extension is already outputting buttons for PayLater (one of Paypal's) latest credit solutions:

<img width="870" alt="Schermata 2020-10-06 alle 16 04 51" src="https://user-images.githubusercontent.com/167670/95219159-589d0700-07f5-11eb-8747-7cf94528acde.png">

(thanks @seand7565 for the screenshot I stole from you during a call 😛)

So in a way this is already working. But we know we should make a few changes:

- add data-partner-attribution-id (https://developer.paypal.com/docs/platforms/checkout/reference/javascript-sdk/#script-parameters)
- enable messaging so credit information can be displayed (https://developer.paypal.com/docs/limited-release/sdk-credit-messaging/integrate)

After both are done everything should be QAed in some way.

**Comment by mtylty** [comment]
This can probably be closed as soon as we get the final QA approval.

**Comment by seand7565** [comment]
We have final approval, so I'll close this issue! 🚀
